name: Run Tests

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create users file
        run: echo "${{ secrets.TEST_USERS }}" > test-data/users.js

      - name: Run tests
        run: npm test
