name: Run Tests

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Debug files
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Create users file
        run: |
          mkdir -p test-data
          cat <<EOF > test-data/users.js
          ${{ secrets.TEST_USERS }}
          EOF

      - name: Run tests
        run: npm test
